server:
  port: 8081

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 6600Fold
    url: jdbc:mysql://mysql-service:3306/microservices?allowPublicKeyRetrieval=true&useSSL=false&useLegacyDatetimeCode=false&serverTimezone=UTC
    baseurl: http://microservices.users.se
  zipkin:
    base-url: http://localhost:9411
  application:
    name: microservices-users
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update